version: '3'

services:
  flask_movie_finder:
    container_name: MovieFinder
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./config:/app/config
    ports:
      - '5000:5000'
    network_mode: host
